:concurrency: 1
staging:
  :concurrency: <%= ENV['RAILS_MAX_THREADS'].to_i || 7 %>
production:
  :concurrency: <%= ENV['RAILS_MAX_THREADS'].to_i || 7 %>
:queues:
  - mailers
  - high
  - default
  - low
